version: 2.1
jobs:
  shapecheck:
    working_directory: ~/oslc-specs
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: ShapeChecker Gradle build
          command: cd tools/ShapeChecker && ./gradlew --console=plain installDist
          condition: always()
      - run:
          name: Check shapes & vocabs for Core
          command: cd tools/ShapeChecker && ./scripts/check-core.sh
          when: always
      - run:
          name: Check shapes & vocabs for Config Mgt
          command: cd tools/ShapeChecker && ./scripts/check-config.sh
          when: always
      - run:
          name: Check shapes & vocabs for AM
          command: cd tools/ShapeChecker && ./scripts/check-am.sh
          when: always
      - run:
          name: Check shapes & vocabs for CM
          command: cd tools/ShapeChecker && ./scripts/check-cm.sh
          when: always
      - run:
          name: Check shapes & vocabs for QM
          command: cd tools/ShapeChecker && ./scripts/check-qm.sh
          when: always
      - run:
          name: Check shapes & vocabs for RM
          command: cd tools/ShapeChecker && ./scripts/check-rm.sh
          when: always
      - run:
          name: Check shapes & vocabs for TRS
          command: cd tools/ShapeChecker && ./scripts/check-trs.sh
          when: always
  prettier:
    working_directory: ~/oslc-specs
    docker:
      - image: node:lts
    steps:
      - checkout
      - run:
          name: Install prettier
          command: npm install --global prettier@2.0.5
      - run:
          name: Check Core spec formatting
          command: prettier --check specs/core/
          when: always
      - run:
          name: Check Query spec formatting
          command: prettier --check specs/query/
          when: always
      - run:
          name: Check Config Mgt spec formatting
          command: prettier --check specs/config/
          when: always
      - run:
          name: Check AM spec formatting
          command: prettier --check specs/am/
          when: always
      - run:
          name: Check CM spec formatting
          command: prettier --check specs/cm/
          when: always
      - run:
          name: Check QM spec formatting
          command: prettier --check specs/qm/
          when: always
      - run:
          name: Check RM spec formatting
          command: prettier --check specs/rm/
          when: always
      - run:
          name: Check TRS spec formatting
          command: prettier --check specs/trs/
          when: always
workflows:
  spec-check:
    jobs:
      - shapecheck
      - prettier
